# Generated by Django 4.1.5 on 2023-01-26 21:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('data_file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['csv', 'xlsx'])])),
            ],
        ),
    ]
